version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: windahtolcipularang
      POSTGRES_DB: data_kepegawaian
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: data_kepegawaian
      DB_USER: postgres
      DB_PASS: windahtolcipularang
    ports:
      - "3000:3000"

volumes:
  pgdata:
